---
- name: Playbook for handling set up of ohmyzsh
  hosts: 127.0.0.1

  tasks:
    - name: Register root directory
      shell: "cd ~ && pwd"
      register: root_dir

    - name: Ensure oh-my-zsh has been installed
      stat:
        path: "{{ root_dir }}/.oh-my-zsh"
      register: oh_my_zsh_result

    - name: Install oh-my-zsh if does not exist
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      when: not oh_my_zsh_result.stat.exists
